SELECT COUNT(LOGDEVDESCRP) AS 'ALARMS', LOGDEVDESCRP, INSTALLED FROm EV_LOG
INNER JOIN AL_PTS ON AL_PTS.ADDR = EV_LOG.EVNT_ADDR
INNER JOIN AL_TYP ON AL_PTS.ALTYP = AL_TYP.ID
INNER JOIN LOGICAL_DEV_D ON EV_LOG.LOGDEVID = LOGICAL_DEV_D.ID
WHERE AL_TYP.ALARM_PROC = 'Y'
GROUP BY LOGDEVDESCRP, INSTALLED
ORDER BY ALARMS DESC